server:
  port: 8080
  #  ssl:
  #    enabled: true
  #    key-store: src/main/resources/bootsecurity.p12
  #    key-store-password: bootsecurity
  #    key-store-type: PKCS12
  #    key-alias: bootsecurity
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-jwt-server?serverTimezone=UTC&useSSL=false
    username: test-jwt-user
    password: jwt123@
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 800121055268-l62imqln6a2bbssu8724maah34kf6iam.apps.googleusercontent.com
            client-secret: 3J009H0F3C6N-rljLBU4JkjN
            scope:
              - email
              - profile
          facebook:
            client-id: 500998490959052
            client-secret: 2d6afa26391350428f639342bf6bbab3
            scope:
              - email
              - public_profile

          naver:
            client-id: PR4P2XCnev0vN0pgZvYu
            client-secret: dcrkxSFpuR
            scope:
              - name
              - email
#              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 3f0a21f64d23a995c0ddf70b117b44e7
            client-secret: HtU4ahZ3dkPVUd9ml1wpdZFqvLbCsAHx
            scope:
              - profile_nickname
#              - profile
              - account_email
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        # naver라는 provider가 OAuth Client에 등록되어 있지 않아서 등록해줌
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id